# Site settings
title: João Junior
description: "Business Card Page"
url: "https://joao.junior.github.io/"
baseurl: ""
profilepic: "/images/j.jpeg"
bkimage: "/images/cover1.jpeg"
google_analytics: UA-XXXXXX-X
font_awesome: "XXXXXXXXXX.js"

author:
  name: "João Junior"
  email: juniorgtr123@gmail.com
  # twitter_username:
  facebook_username: João Junior
  github_username: jjunieko
  linkedin_username: joão-júnior-72a6a2172
  instagram_username: joao.juniordev

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ["README.md", "screenshot-overview.png"]
